# Generated by Django 4.1.3 on 2022-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0003_remove_az_id_remove_dk_id_remove_mc_id_remove_sc_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=2)),
                ('empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='az',
        ),
        migrations.DeleteModel(
            name='dk',
        ),
        migrations.DeleteModel(
            name='mc',
        ),
        migrations.DeleteModel(
            name='sc',
        ),
        migrations.DeleteModel(
            name='st',
        ),
    ]
