# Generated by Django 4.1.3 on 2022-11-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0004_menu_delete_az_delete_dk_delete_mc_delete_sc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
