# Generated by Django 4.1.3 on 2022-11-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0005_menu_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='recommend',
        ),
    ]
