# Generated by Django 4.1.3 on 2022-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0006_remove_menu_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(to='ddposmenus.category'),
        ),
    ]
