# Generated by Django 4.1.3 on 2022-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0007_category_remove_menu_category_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='mc', max_length=2),
            preserve_default=False,
        ),
    ]
