# Generated by Django 4.1.3 on 2022-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0008_remove_menu_category_delete_category_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
