# Generated by Django 4.1.3 on 2022-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0009_menu_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(default='mull', upload_to='testupload/'),
            preserve_default=False,
        ),
    ]
