# Generated by Django 4.1.3 on 2022-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddposmenus', '0010_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(upload_to='../ddposfrontend/src/asset/image/menus/'),
        ),
    ]
